### ISSUE TITLE
Pass Circle CI Tests

### ISSUE THREAD

**Issue by MiguhRuiz** [nodefruit/fruit-rethinkdb#2]
Any ideas to help me in order to pass Circle CI tests?

[https://circleci.com/gh/nodefruit/fruit-rethinkdb](https://circleci.com/gh/nodefruit/fruit-rethinkdb)

**Comment by Javascipt** [comment]
It seems that node wasn't installed properly since the npm command line isn't known. I don't know if it has something to do with the node version. have you tried with a lower version ?

**Comment by MiguhRuiz** [comment]
I've written the same version as I use on my Macbook and the test pass correctly here.

**Comment by Javascipt** [comment]
[This](https://discuss.circleci.com/t/bug-npm-not-working-correctly/428/2) might probably help you. Please let me know if you still habe the same issue.

**Comment by MiguhRuiz** [comment]
I will be try to solve it. I'll revise the link too.
Sorry for the delay 😞

**Comment by MiguhRuiz** [comment]
Solved. Commits involved:
e04dba0348a8963f9931a680c486fe9e94e2badd
38bd5d0784ca76b87feea02926c9db34b76785aa
51eca5024d52137e686554cf7e38d2a46fe8c653
